
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with local PostgreSQL
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=camunda
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Camunda 7 Platform with Keycloak Plugin
  camunda:
    # build:
    #   context: ./docker/camunda
    #   dockerfile: Dockerfile
    image: camunda/camunda-bpm-platform:7.20.0
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA_UPDATE=true
      - CAMUNDA_BPM_ADMIN_USER_ID=admin
      - CAMUNDA_BPM_ADMIN_USER_PASSWORD=admin
      - CAMUNDA_BPM_ADMIN_USER_FIRST_NAME=Admin
      - CAMUNDA_BPM_ADMIN_USER_LAST_NAME=User
      - CAMUNDA_BPM_ADMIN_USER_EMAIL=admin@netbuild.local
      # Keycloak Plugin Environment Variables
      - KEYCLOAK_URL=http://keycloak:8081
      - KEYCLOAK_REALM=netbuild
      - KEYCLOAK_CLIENT_ID=camunda-identity-service
      - KEYCLOAK_CLIENT_SECRET=camunda-secret-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      # keycloak:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HTTP_PORT=8081
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command: start-dev --http-port=8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # NetBuild UI (Next.js) - for future use
  # netbuild:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - CAMUNDA_API_URL=http://camunda:8080/engine-rest
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/camunda
  #   depends_on:
  #     - camunda
  #     - postgres

volumes:
  postgres_data:
    driver: local