#!/bin/bash

echo "Setting up Keycloak for Camunda integration..."
echo "============================================"
echo ""
echo "This script will guide you through setting up Keycloak for Camunda."
echo ""

# Wait for Keycloak to be ready
echo "Waiting for Keycloak to be ready..."
until curl -s -f -o /dev/null http://localhost:8081/health/ready; do
  echo -n "."
  sleep 5
done
echo " Ready!"

echo ""
echo "Please access Keycloak Admin Console: http://localhost:8081/admin"
echo "Login with: admin/admin"
echo ""
echo "Then follow these steps:"
echo ""
echo "1. Create the Camunda Client:"
echo "   - Go to Clients → Create"
echo "   - Client ID: camunda-identity-service"
echo "   - Client Protocol: openid-connect"
echo "   - Access Type: confidential"
echo "   - Service Accounts Enabled: ON"
echo "   - Valid Redirect URIs: http://localhost:8080/*"
echo "   - Web Origins: http://localhost:8080"
echo ""
echo "2. Get the Client Secret:"
echo "   - Go to the Credentials tab"
echo "   - Copy the Secret value"
echo "   - Update docker-compose.yml with: KEYCLOAK_CLIENT_SECRET=<copied-secret>"
echo ""
echo "3. Create Roles for Camunda:"
echo "   - Go to Roles → Add Role"
echo "   - Create these roles:"
echo "     • camunda-admin"
echo "     • camunda-user"
echo "     • accounting"
echo "     • management"
echo "     • sales"
echo ""
echo "4. Create Demo Users (optional for testing):"
echo "   - Go to Users → Add User"
echo "   - Create users: demo, john, mary, peter"
echo "   - Set passwords and assign appropriate roles"
echo ""
echo "5. Update your .env.local:"
echo "   KEYCLOAK_CAMUNDA_CLIENT_SECRET=<copied-secret-from-step-2>"
echo ""
echo "After completing these steps, restart the Docker containers:"
echo "docker-compose down"
echo "docker-compose up --build"
echo ""